image_annotation/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


app_name = 'image_annotation'

urlpatterns = [
    # /music/
    path('', views.home_page, name='home_page'),
    path('sign_up/', views.UserRegister.as_view(), name='signup'),
    path('main_page/', views.main_page, name='main_page'),
    path('', include('django.contrib.auth.urls')),
    path('create_image/', views.create_image, name='create_image'),
    path('load_image/', views.load_image, name='load_image'),
    path('add_rule/', views.add_rule, name='add_rule'),
    path('get_image/', views.get_image, name='get_image'),
    path('get_owner_image/', views.get_owner_image, name='get_owner_image'),
    path('set_default/', views.set_default, name='set_default'),
    path('del_rule/', views.del_rule, name='del_rule'),
    path('usergroups/', views.usergroups, name='usergroups'),
    path('add_user/', views.add_user, name='add_user'),
    path('add_group/', views.add_group, name='add_group'),
    path('del_user/', views.del_user, name='del_user'),
    path('del_group/', views.del_group, name='del_group'),
    path('get_groups/', views.get_groups, name='get_groups'),
    path('get_users/', views.get_users, name='get_users'),
    path('set_password/', views.set_password, name='set_password'),
    path('is_member/', views.is_member, name='is_member'),
    path('log_out/', views.log_out, name='log_out'),
]

phase3/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_annotation.urls')),
]

image_annotation/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image, ImageFilter
import ast
import io
import re
from .helper import *

# Create your models here.
"""class Group(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class MyUser(models.Model):

    name = models.CharField(max_length=50)
    groups = models.ManyToManyField(Group)
    password = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)"""

class LabeledImage(models.Model):
    name = models.CharField(max_length=50, unique=True)
    image = models.ImageField(upload_to = 'static/uploaded_images/')
    action = models.CharField(max_length=10) # ALLOW, DENY, BLUR
    ruleList = models.CharField(max_length=5000) # can be a lot of rules
    owner = models.ForeignKey(User, null = False, on_delete=models.CASCADE) # Every image has one owner

    def __str__(self):
        return str(self.name)

    def setImage(self,buf):  # Set image content from binary buffer
        self.image = buf


    def loadImage(self,filepath):  # we can save image as bytearray to make it easier for us to modification and database operations

        try:
            with open(filepath, "rb") as img:
                self.image = bytearray(img.read())

        except IOError:
            print("Couldn't find the image in given path: " + filepath)


    def load(self,name):
        im = LabeledImage.objects.get(name=name)
        self.name = im.name
        self.image = im.image
        self.action = im.action
        self.ruleList = im.ruleList
        self.owner = im.owner


    def setDefault(self,action):
        self.action = action


    def addRule(self,matchexpr, shape, action, pos = -1):
        pos = int(pos)
        shape = ast.literal_eval(shape)
        if self.ruleList == '':
            rules = []
        else:
            rules = ast.literal_eval(self.ruleList)  #Convert string back to list

        rule = (matchexpr, shape, action)
        if pos == -1:
            rules.append(rule)
        else:
            rules.insert(pos, rule)

        self.ruleList = str(rules) #Convert list to str
        return rule


    def delRule(self,pos):
        rules = ast.literal_eval(self.ruleList)  #Convert string back to list
        del rules[pos]
        self.ruleList = str(rules) #Convert list to str


    def getImage(self,user):

        user = User.objects.get(username=user)

        im = Image.open(self.image)
        width,height = im.size

        if self.ruleList == '':
            if self.action == 'ALLOW':
                return im
            rules = []
        else:
            rules = ast.literal_eval(self.ruleList)  #Convert string back to list

        blurred_image =  im.filter(ImageFilter.BLUR)

        for w in range(width):
            for h in range(height):
                matchFound = False
                for rule in rules:
                    if rule[1][0].upper() == "CIRCLE":# get user groups and check for match
                        if insideCircle(w,h,rule[1]) and (re.fullmatch(rule[0],user.username) or matchGroup(user,rule)):
                            action = rule[2]
                            if action.upper() == "DENY":
                                im.putpixel( (w,h), (0,0,0))
                            elif action.upper() == "BLUR":
                                im.putpixel( (w,h), blurred_image.getpixel((w,h)))
                            matchFound = True
                            break;

                    elif rule[1][0].upper() == "RECTANGLE":
                        if insideRectangle(w,h,rule[1]) and (re.fullmatch(rule[0],user.username) or matchGroup(user,rule)):
                            action = rule[2]
                            if action.upper() == "DENY":
                                im.putpixel( (w,h), (0,0,0))
                            elif action.upper() == "BLUR":
                                im.putpixel( (w,h), blurred_image.getpixel((w,h)))
                            matchFound = True
                            break;

                    elif rule[1][0].upper() == "POLYLINE":
                        if insidePolyline(w,h,rule[1]) and (re.fullmatch(rule[0],user.username) or matchGroup(user,rule)):
                            action = rule[2]
                            if action.upper() == "DENY":
                                im.putpixel( (w,h), (0,0,0))
                            elif action.upper() == "BLUR":
                                im.putpixel( (w,h), blurred_image.getpixel((w,h)))
                            matchFound = True
                            break;
                if not matchFound: #Apply defaultAction if none of the rules match
                    if self.action.upper() == "DENY":
                        im.putpixel( (w,h), (0,0,0))
                    elif self.action.upper() == "BLUR":
                        im.putpixel( (w,h), blurred_image.getpixel((w,h)))

        return im

image_annotation/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        help_texts = {'username':None,}
        fields = ['username', 'password']

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

image_annotation/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.contrib.auth.models import User, Group
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.core.files.images import get_image_dimensions
from PIL import Image
from .forms import  UserForm, ImageUploadForm
from .models import *
from .image_list import *
import ast, json

# Create your views here.
def home_page(request):
    return render(request, 'image_annotation/home_page.html')

def main_page(request):
    imList = imageList()
    return render(request, 'image_annotation/image_list.html', {"imList" : imList})

def create_image(request):
    if request.method == "POST":
        image_name = request.POST['image_name']
        defaultAction = "ALLOW"
        image = LabeledImage(name=image_name,owner=request.user,action=defaultAction)
        image.save()
        rules = []
        return render(request, 'image_annotation/main_page.html', {"image_name" : image_name, "rules":rules})

def load_image(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image_name = request.POST['image_name']
            img = LabeledImage.objects.get(name=image_name)
            img.ruleList = ''
            img.image = form.cleaned_data['image']
            img.save()
            width, height = get_image_dimensions(img.image.file)
            response = {"url": '/'+img.image.url, "width":width, "height":height}
            return JsonResponse(response, safe=False)


def add_rule(request):
    if request.method == "POST":
        image_name = request.POST['image_name']
        username = request.POST['username']
        shape = request.POST['shape']
        shape_pos = request.POST['shape_pos']
        action = request.POST['action']
        rule_pos = request.POST['rule_pos']
        final_shape = '(\'' + shape + '\',' + shape_pos + ')'
        image = LabeledImage.objects.get(name=image_name)
        if request.user.username ==  image.owner.username:
            if rule_pos == "":
                rule = image.addRule(username, final_shape, action)
            else:
                rule = image.addRule(username, final_shape, action, int(rule_pos))
            image.save()
            return JsonResponse(json.dumps(rule), safe=False)
        else:
            return render(request, 'image_annotation/not_authorized.html',{"image_name" : image_name})


def get_image(request):
    if request.method == "POST":
        if request.POST['username'] == request.user.username: # Now user can edit the image, addrules etc.
            image_name = request.POST['image_name']
            image = LabeledImage.objects.get(name=image_name)

            if image.ruleList == '':
                rules = []
            else:
                rules = ast.literal_eval(image.ruleList)  #Convert string back to list

            if (image.image):
                url = '/' + image.image.url
                width, height = get_image_dimensions(image.image.file)
                return render(request, 'image_annotation/main_page.html', {"image_name" : image_name, "rules":rules, "url":url, "width":width, "height":height})
            else:
                return render(request, 'image_annotation/main_page.html', {"image_name" : image_name, "rules":rules})

        else: # Now user only can get the Image
            image_name = request.POST['image_name']
            image = LabeledImage.objects.get(name=image_name)
            img = image.getImage(request.user.username)
            w, h = img.size
            username = request.user.username
            img.save(settings.BASE_DIR + settings.STATIC_URL + "images/" + username + ".png")
            #return render(request, 'image_annotation/render_image.html')
            return render(request, 'image_annotation/render_image.html', {"w" : w, "h" : h, "username" : username})

def get_owner_image(request):
    if request.method == "POST":
        image_name = request.POST['image_name']
        image = LabeledImage.objects.get(name=image_name)
        img = image.getImage(request.user.username)
        w, h = img.size
        username = request.user.username
        img.save(settings.BASE_DIR + settings.STATIC_URL + "images/" + username + ".png")
        return render(request, 'image_annotation/render_image.html', {"w" : w, "h" : h, "username" : username})

def set_default(request):
    if request.method == "POST":
        image_name = request.POST['image_name']
        image = LabeledImage.objects.get(name=image_name)
        if request.user.username == image.owner.username:
            image.action = request.POST['action']
            image.save()
            return HttpResponse('')
        else:
            return render(request, 'image_annotation/not_authorized.html',{"image_name" : image_name})

def del_rule(request):
    if request.method == "POST":
        image_name = request.POST['image_name']
        image = LabeledImage.objects.get(name=image_name)
        if request.user.username == image.owner.username:
            rule = ast.literal_eval(request.POST['rule'])
            rules = ast.literal_eval(image.ruleList)  #Convert string back to list
            idx = rules.index(rule)
            image.delRule(idx)
            del rules[rules.index(rule)]
            image.save()
            return HttpResponse('')
            #return render(request, 'image_annotation/main_page.html',{"image_name" : image_name,"rules":rules})
        else:
            return render(request, 'image_annotation/not_authorized.html',{"image_name" : image_name})

def usergroups(request):
    if request.method == "POST":
        groups = list(Group.objects.all())
        users = list(User.objects.all())
        if request.user.is_superuser:
            return render(request, "image_annotation/superuser.html", {"users":users, "groups":groups})
        else :
            return render(request, "image_annotation/user_groups.html", {"users":users, "groups":groups})

def add_user(request):
    if request.method == "POST":
        username = request.POST['username']
        groups = request.POST['groups']
        password = request.POST['password']
        usr = User(username=username)
        usr.set_password(password)
        usr.save()

        groups = ast.literal_eval(groups)
        for group in groups:
            try:
                Group.objects.get(name=group)
            except:
                Group.objects.create(name=group)
            gr = Group.objects.get(name=group)
            gr.user_set.add(usr)

        return HttpResponse('')

def add_group(request):
    if request.method == "POST":
        groupname = request.POST['groupname']
        try:
            Group.objects.get(name=groupname)
        except:
            Group.objects.create(name=groupname)

        return HttpResponse('')

def del_user(request):
    if request.method == "POST":
        username = request.POST['username']
        try:
            User.objects.get(username=username).delete()
        except:
            pass

        return HttpResponse('')

def del_group(request):
    if request.method == "POST":
        groupname = request.POST['groupname']
        try:
            Group.objects.get(name=groupname).delete()
        except:
            pass

        return HttpResponse('')

def get_groups(request):
    if request.method == "POST":
        username = request.POST['username']
        usr = User.objects.get(username=username)
        groups = list(usr.groups.all())
        return render(request, "image_annotation/show_groups.html", {"groups" : groups})

def get_users(request):
    if request.method == "POST":
        groupname = request.POST['groupname']
        group = Group.objects.get(name=groupname)
        users = list(group.user_set.all())
        return render(request, "image_annotation/show_users.html", {"users" : users})
def set_password(request):
    if request.method == "POST":
        if request.user.is_superuser:
            username = request.POST['username']
        else:
            username = request.user.username
        password = request.POST['password']

        usr = User.objects.get(username=username)
        usr.set_password(password)
        usr.save()

        groups = list(Group.objects.all())
        users = list(User.objects.all())
        if request.user.is_superuser:
            return render(request, "image_annotation/superuser.html", {"users":users, "groups":groups})
        else:
            return render(request, "image_annotation/user_groups.html", {"users":users, "groups":groups})

def is_member(request):
    if request.method == "POST":
        username = request.POST['username']
        groupname = request.POST['groupname']

        usr = User.objects.get(username=username)
        val = usr.groups.filter(name=groupname).exists()
        return render(request, "image_annotation/is_member.html", {"val":val})

def log_out(request):
    logout(request)
    return redirect('/')


class UserRegister(View):
    form_class = UserForm
    template_name = 'image_annotation/registration_form.html'

    # display a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            return redirect('/login')

        return render(request, self.template_name , {'form' : form})

image_annotation/templates/image_annotation/home_page.html
<input type="submit" value="SIGN UP" onclick="location.href = '/sign_up';" style="font-size : 50px; width : %100; height : 150px;"  /><br>
<input type="submit" value="SIGN IN" onclick="location.href = '/login';" style="font-size : 50px; width : %100; height : 150px;"  />

image_annotation/templates/image_annotation/image_list.html
<form action="/log_out" class="inline">
  <button>Log out</button>
</form>
<h2>Create new image</h2>
<form action = "/create_image/" method='POST'> {% csrf_token %}
    Image name: <input type="text" name="image_name" required><br>
    <input type='submit' value='Create image'>
</form>
<br><br>
<h2>UserGroups</h2>
<form action = "/usergroups/" method='POST'> {% csrf_token %}
    <input type='submit' value='UserGroup operations'>
</form>
<br><br>

<u1>
  <h2>Select image</h2>
  {% for item in imList %}
  <form action = "/get_image/" method='POST'> {% csrf_token %}
    <input type='hidden' name='username' value={{ item.username }}>
    <input type='hidden' name='image_name' value={{ item.imagename }}>
    <h3>Owner: {{item.username}}</h3> <input type='submit' value={{ item.imagename }}><br>
  </form>
  {% endfor %}
</u1>

image_annotation/templates/image_annotation/is_member.html
<h1> {{ val }} </h1>
<form action = "/usergroups/" method='POST'> {% csrf_token %}
  <input type='submit' value="Back"><br>
</form>

image_annotation/templates/image_annotation/main_page.html
<style>
  body {
    background-color: powderblue;
  }
  #imagediv {
    position : fixed;
    left : 700px;
    top : 100px;
  }
  #image_canvas {
    position:fixed;
    left : 700px;
    top : 100px;
    z-index:20;
  }
  #clear_canvas {
    position: relative;
  }
</style>
<h3>Main Page</h3>
<form action="/main_page" class="inline">
  <button>Home</button>
</form>
<div class="image_div" id='imagediv'>
  {% if url %}
    <img src={{ url }} id="user_image">
    <canvas id="image_canvas" width={{ width }} height={{ height }}></canvas></br>
  {% else %}
    <img id="user_image">
    <canvas id="image_canvas"></canvas></br>
  {% endif %}
  <input type="button" onclick="clearCanvas()" id="clear_canvas" value="Clear">
</div>
<h2>Load Image</h2>
<form id="load_image" enctype="multipart/form-data">{% csrf_token %}
    <input id="image_name" type="hidden" name="image_name" value={{ image_name }}>
    <input id="id_image" type="file" class="" name="image" accept="image/*">
    <input type="submit" value="Upload" />
</form>
<h2>Add Rule</h2>
<form id='add_rule'> {% csrf_token %}
    <input type="hidden" id='imgname' name="image_name" value={{ image_name }}><br>
    Username: <input type="text" id='usrname' name="username" required><br>
    Shape:    <select name="shape" id="shape">
    <option value="CIRCLE">CIRCLE</option>
    <option value="RECTANGLE">RECTANGLE</option>
    <option value="POLYLINE">POLYLINE</option>
    </select><br/>
    Action:   <select name="action" id="action">
    <option value="ALLOW">ALLOW</option>
    <option value="DENY">DENY</option>
    <option value="BLUR">BLUR</option>
    </select><br/>
    Rule Position: <input type="number" id="rule_pos" step="1" name="rule_pos"><br>
    <input type='submit' value='Add Rule'>
</form>
<h2>Set default action</h2>
<form id="set_default"> {% csrf_token %}
    <input type="hidden" id="iname" name="image_name" value={{ image_name }}>
    Default Action:   <select name="action" id="default_action">
    <option value="ALLOW">ALLOW</option>
    <option value="DENY">DENY</option>
    <option value="BLUR">BLUR</option>
    </select><br/>
    <input type='submit' value='Set Default'>
</form>
<h2>Del Rule</h2>
<form id="del_rule"> {% csrf_token %}
    <input type="hidden" id="imname" name="image_name" value={{ image_name }}>
    <ul id="rule_list">
      {% for rule in rules %}
        <li class='{{ rule }}'><input type="radio" class="rule_select" name="rule" value="{{ rule }}">{{ rule }}</li>
      {% endfor %}
    </ul>
    <input type="submit" value='Del Rule'>
</form>
<h2>Get Image</h2>
<form action='/get_owner_image/' method='POST'> {% csrf_token %}
    <h3>Please load an image if you haven't done it before</h3>
    <input type="hidden" name="image_name" value={{ image_name }}><br>
    <input type='submit' value='Get Image'>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript">

$(document).on('submit','#set_default', function(e){
  e.preventDefault();

  var def_act = $('#default_action option:selected').val();
  $.ajax({
    type:'POST',
    url:'/set_default/',
    data: {
      image_name:$('#iname').val(),
      action:def_act,
      csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
    },
    success:function(){
        alert("Default action is set as " + def_act);
    }
  });
});

</script>

<script type="text/javascript">
  $(document).on('submit','#del_rule', function(e){
    e.preventDefault();

    var selected_rule = $(".rule_select:checked").val();
    $.ajax({
      type:'POST',
      url:'/del_rule/',
      data: {
        image_name:$('#imname').val(),
        rule:$(".rule_select:checked").val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success:function(){
          $("#rule_list li").remove(':contains(' + selected_rule + ')')
          alert("Rule deleted!");
      }
    });
  });
</script>

<script type="text/javascript">

var pos;

function drawCircle(x1, y1, x2, y2) {

    var radiusX = (x2 - x1) * 0.5,   /// radius for x based on input
        radiusY = (y2 - y1) * 0.5,   /// radius for y based on input
        step = 0.01,                 /// resolution of ellipse
        a = step,                    /// counter
        pi2 = Math.PI * 2 - step;    /// end angle

    var centerX, centerY, radius;

    if(x2 - x1 > y2 - y1) {
      radius = (y2 - y1) * 0.5
    } else {
      radius = (x2 - x1) * 0.5
    }

    centerX = x1 + radius;
    centerY = y1 + radius;


    ctx.beginPath();

    ctx.moveTo(centerX + radius * Math.cos(0),
               centerY + radius * Math.sin(0));

    /// create the ellipse
    for(; a < pi2; a += step) {
        ctx.lineTo(centerX + radius * Math.cos(a),
                   centerY + radius * Math.sin(a));
    }

    pos =  String(Math.floor(Math.abs(centerX))) + ',' + String(Math.floor(Math.abs(centerY))) + ',' + String(Math.floor(Math.abs(radius)));
    /// close it and stroke it for demo
    ctx.closePath();
    ctx.strokeStyle = '#000';
    ctx.stroke();
}

function drawRectangle(x1, y1, x2, y2) {
  ctx.beginPath();

  ctx.moveTo(x1, y2);
  ctx.lineTo(x1 , y1);
  ctx.moveTo(x2, y1);
  ctx.lineTo(x1 , y1);
  ctx.moveTo(x1 , y2);
  ctx.lineTo(x2,y2);
  ctx.moveTo(x2,y1);
  ctx.lineTo(x2,y2);

  pos =  String(Math.floor(Math.abs(x1))) + ',' + String(Math.floor(Math.abs(y1))) + ',' + String(Math.floor(Math.abs(x2))) + ',' + String(Math.floor(Math.abs(y2)));

  ctx.closePath();
  ctx.strokeStyle = '#000';
  ctx.stroke();
}

function drawLine(x1, y1, x2, y2) {
  ctx.beginPath();
  ctx.moveTo(x1,y1);
  ctx.lineTo(x2,y2);

  ctx.closePath();
  ctx.strokeStyle = '#000';
  ctx.stroke();
}

var canvas = document.getElementById('image_canvas'),
    ctx = canvas.getContext('2d'),
    w = canvas.width,
    h = canvas.height,
    x1,                 /// start points
    y1,
    isDown = false;     /// if mouse button is down
    polylinePoints = [];

function clearCanvas() {
    ctx.clearRect(0, 0, w, h);
    polylinePoints = [];
}
/// handle mouse down
canvas.onmousedown = function(e) {

    /// get corrected mouse position and store as first point
    var rect = canvas.getBoundingClientRect();
    x1 = e.clientX - rect.left;
    y1 = e.clientY - rect.top;
    isDown = true;

}

/// clear isDown flag to stop drawing
canvas.onmouseup = function(e) {
    isDown = false;

    if($('#shape option:selected').val() == 'POLYLINE') {
      var rect = canvas.getBoundingClientRect(),
          x2 = e.clientX - rect.left,
          y2 = e.clientY - rect.top;

      drawLine(x1,y1,x2,y2);
      polylinePoints.push(x1);
      polylinePoints.push(y1);
      console.log(polylinePoints)
    }

}

/// draw ellipse from start point
canvas.onmousemove = function(e) {

    if (!isDown) {
      return;
    }

    var rect = canvas.getBoundingClientRect(),
        x2 = e.clientX - rect.left,
        y2 = e.clientY - rect.top;

    if($('#shape option:selected').val() == 'CIRCLE') {
      clearCanvas();
      drawCircle(x1, y1, x2, y2);
    } else if($('#shape option:selected').val() == 'RECTANGLE') {
      clearCanvas();
      drawRectangle(x1, y1, x2, y2);
    }
}

$(document).on('submit','#add_rule', function(e){
  e.preventDefault();
  var selected_shape = $('#shape option:selected').val();
  var selected_action = $('#action option:selected').val();

  if(selected_shape == 'POLYLINE') {
    if(polylinePoints.length == 0) {
      return;
    }
    pos = "[";
    for(var i = 0; i < polylinePoints.length - 2; i = i+2) {
      pos += '(' + polylinePoints[i] + ', ' + polylinePoints[i+1] + '), ';
    }
    pos += '(' + polylinePoints[i] + ', ' + polylinePoints[i+1] + ')]';
    polylinePoints = [];
  }

  $.ajax({
    type:'POST',
    url:'/add_rule/',
    data: {
      image_name:$('#imgname').val(),
      username:$('#usrname').val(),
      shape: selected_shape,
      shape_pos: pos,
      action: selected_action,
      rule_pos:$('#rule_pos').val(),
      csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
    },
    success:function(data){
        if(selected_shape == 'POLYLINE') {
          var final_shape = '(\'' + selected_shape + '\', ' + pos + ')'; // ("POLYLINE", [(25, 25), (25, 50), (50, 50)])
          var final_rule = '(\'' + $('#usrname').val() + '\', ' + final_shape + ', \'' + selected_action + '\')';   // ("ali",("POLYLINE",[(25,25),(25,50),(50,50)]),"DENY")
          $("#rule_list").append('<li class=' + final_rule + '><input type=\'radio\' class=\'rule_select\' name=\'rule\' value=\"' + final_rule + '\">' + final_rule + '</li>')
        } else {
          data = data.replace(/\[/g ,'(');
          data = data.replace(/\]/g ,')');
          data = data.replace(/\"/g, '\'')
          $("#rule_list").append('<li class=' + data + '><input type=\'radio\' class=\'rule_select\' name=\'rule\' value=\"' + data + '\">' + data + '</li>')
        }
        alert("Rule added!");
    }
  });
});

$(document).on('submit','#load_image', function(e){
  e.preventDefault();

  var formData = new FormData();
  var image = $('input[type=file]')[0].files[0]
  formData.append("image", image);
  formData.append("image_name", $('#image_name').val());
  formData.append("csrfmiddlewaretoken", $('input[name=csrfmiddlewaretoken]').val());

  $.ajax({
    type:'POST',
    url:'/load_image/',
    data: formData,
    cache: false,
    processData: false,
    contentType: false,
    success:function(response){
        var url = response.url
        var image_width = response.width
        var image_height = response.height
        var img = $('#user_image');
        img.attr('src', url);
        img.attr('width', image_width);
        img.attr('height', image_height);
        $('#image_canvas').attr('width', image_width);
        $('#image_canvas').attr('height', image_height);
        $('#rule_list li').remove();
        w = image_width;
        h = image_height;
        alert("Image uploaded successfully");
    },
    error:function(){
        alert("Failed to upload image");
    }
  });
});

</script>

image_annotation/templates/image_annotation/not_authorized.html
<h2>You are not authorized to perform this action</h2><br>
<form action="/main_page" class="inline">
  <button>Home</button>
</form>

image_annotation/templates/image_annotation/registration_form.html
<h2>Register</h2>
<form method='POST'> {% csrf_token %}
    {{ form }}
    <input type='submit' value='Sign up'>
</form>

image_annotation/templates/image_annotation/render_image.html
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>
<body>
  <form action="/main_page" class="inline">
    <button>Home</button>
  </form>
  {% load static %}
  <img src="{% static "/images/" %}{{ username }}.png" alt="My image"  width={{ w }} height={{ h }}>
</body>
</html>

image_annotation/templates/image_annotation/show_groups.html
<u1>
  <h2>User groups</h2>
  {% for group in groups %}
    <h2>{{ group.name }}</h2>
  {% endfor %}
  <form action = "/usergroups/" method='POST'> {% csrf_token %}
    <input type='submit' value="Back"><br>
  </form>
</u1>

image_annotation/templates/image_annotation/show_users.html
<u1>
  <h2>Users</h2>
  {% for user in users %}
    <h2>{{ user.username }}</h2>
  {% endfor %}
  <form action = "/usergroups/" method='POST'> {% csrf_token %}
    <input type='submit' value="Back"><br>
  </form>
</u1>